version: 1.0.{build}
skip_tags: true
configuration: Release
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: PECtFf6HJFflVqz5CrugJpYntoE7GdTDsBv6HhyGoh3x83kRqokRCS7Yj8T4a4ws
before_build:
  - nuget restore "Castle.DynamicLinqQueryBuilder.Tests.sln"
build:
  project: Castle.DynamicLinqQueryBuilder.Tests.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe -register:user "-targetargs:""Castle.DynamicLinqQueryBuilder.Tests\bin\$env:CONFIGURATION\Castle.DynamicLinqQueryBuilder.Tests.dll""" -filter:"+[Castle.DynamicLinqQueryBuilder]*" -excludebyattribute:*.ExcludeFromCodeCoverageAttribute -output:opencoverCoverage.xml

    & new-variable -name coveralls -visibility public -value (Resolve-Path ".\packages\coveralls.net.*\tools\csmacnz.Coveralls.exe").ToString()

    $env:APPVEYOR_BUILD_NUMBER

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
